### ISSUE TITLE
Make an explanation mandatory when vetoing

### ISSUE THREAD

**Issue by dellitsni** [dellitsni/Konsent#56]

**Comment by surrealbytes** [comment]
i thought we gonna leave that for the discussion place. with onymus voting we know who placed a veto.

**Comment by dellitsni** [comment]
I'm splitted on this one... I can imagine people just vetoing and then disappearing. I'll close it again, if it becomes an issue we can always reopen it.

**Comment by surrealbytes** [comment]
we would have problem with this either way, people can just veto and say something like 'asdf ' for the reason :smirk: 

Maybe we should make it so that vetoes can be ignored if the rest of the users choose so or make a vetoing limit? just throwing ideas, i'm not sure at all about this. i think it will make more sense if we move the veto in phase2 or in another phase in between. I'm still slacking at my libredraw with Flow charts and some kind of design for the abstractions, but this is hard af and i only follow the articles about the consensus paradigm atm.
